name: "Setup Rust Environment"
description: "Sets up Rust toolchain with caching"

runs:
  using: "composite"
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561
      with:
        toolchain: stable

    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@510b3ecd7915856b6909305605afa7a8a57c1b04 # v2.48.1
      with:
        tool: cargo-llvm-cov@0.6.16, cargo-nextest@0.9.88

    - name: Setup Rust cache
      uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2
      with:
        # Optional: cache dependencies as well
        cache-on-failure: true
